### ISSUE TITLE
🐛 App closes unexpectedly after initialization

### ISSUE THREAD

**Issue by igperez-ar** [GoogleCloudPlatform/recaptcha-enterprise-react-native#13]
### What's happening?

After trying to initialize the service, the application closes unexpectedly.

### Reproduceable code 

```tsx
import * as React from 'react';
import {
  Button,
  StyleSheet,
  Text,
  View,
} from 'react-native';
import {
  execute,
  initClient,
  RecaptchaAction,
} from '@google-cloud/recaptcha-enterprise-react-native';
import { GCP_RECAPTCHA_KEY_ID } from './utils/constants';

const App = () => {
  const [initResult, setInitResult] = React.useState<string | undefined>();
  const [executeResult, setExecuteResult] = React.useState<string | undefined>();
  const [token, setToken] = React.useState<string | undefined>();

  return (
    <View style={styles.container}>
      <Button
        onPress={() =>
          initClient(GCP_RECAPTCHA_KEY_ID ?? 'key', 10000)
            .then(() => setInitResult('ok'))
            .catch((error) => {
              setInitResult(error.toString());
            })
        }
        title="Init"
        testID="initButtonId"
      />
      <Text>Init Result: </Text>
      <Text testID="initResultId">{initResult}</Text>

      <Button
        onPress={() =>
          execute(RecaptchaAction.LOGIN(), 10000)
            .then((t) => {
              setExecuteResult(t.startsWith('03') ? 'ok' : 'error');
              setToken(t);
            })
            .catch((error) => {
              setExecuteResult(error.toString());
            })
        }
        title="Execute"
        testID="executeButtonId"
      />
      <Text>Execute Result:</Text>
      <Text testID="executeResultId">{executeResult}</Text>
      <Text>Token:</Text>
      <Text testID="tokenId">{token}</Text>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  box: {
    width: 60,
    height: 60,
    marginVertical: 20,
  },
});

export default App;
```

### Relevant logcat output

```shell
2023-10-03 12:41:41.575 29808-29985 PlayCore                app.debug                            I  UID: [10575]  PID: [29808] IntegrityService : requestIntegrityToken(IntegrityTokenRequest{nonce=E_WjF49L5pxMtzoolB7u88n4AbsYexD6m7gb5dco5hg=, cloudProjectNumber=145656491484})
2023-10-03 12:41:41.577 29808-30064 PlayCore                app.debug                            I  UID: [10575]  PID: [29808] IntegrityService : Initiate binding to the service.
2023-10-03 12:41:41.600 29808-29808 PlayCore                app.debug                            I  UID: [10575]  PID: [29808] IntegrityService : ServiceConnectionImpl.onServiceConnected(ComponentInfo{com.android.vending/com.google.android.finsky.integrityservice.IntegrityService})
2023-10-03 12:41:41.603 29808-30064 PlayCore                app.debug                            I  UID: [10575]  PID: [29808] IntegrityService : linkToDeath
2023-10-03 12:41:43.613 29808-29825 PlayCore                app.debug                            I  UID: [10575]  PID: [29808] OnRequestIntegrityTokenCallback : onRequestIntegrityToken
2023-10-03 12:41:43.613 29808-30064 PlayCore                app.debug                            I  UID: [10575]  PID: [29808] IntegrityService : Unbind from service.
2023-10-03 12:42:09.937 29808-29822 JavaBinder              app.debug                            W  BinderProxy is being destroyed but the application did not call unlinkToDeath to unlink all of its death recipients beforehand.  Releasing leaked death recipient: com.google.android.play.integrity.internal.n
2023-10-03 12:42:53.976 29808-29823 StrictMode              app.debug                            D  StrictMode policy violation: android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                                                                      	at android.os.StrictMode$AndroidCloseGuardReporter.report(StrictMode.java:1892)
                                                                                                      	at dalvik.system.CloseGuard.warnIfOpen(CloseGuard.java:286)
                                                                                                      	at java.util.zip.Inflater.finalize(Inflater.java:407)
                                                                                                      	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:289)
                                                                                                      	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:276)
                                                                                                      	at java.lang.Daemons$Daemon.run(Daemons.java:137)
                                                                                                      	at java.lang.Thread.run(Thread.java:919)
                                                                                                      Caused by: java.lang.Throwable: Explicit termination method 'end' not called
                                                                                                      	at dalvik.system.CloseGuard.open(CloseGuard.java:237)
                                                                                                      	at java.util.zip.Inflater.<init>(Inflater.java:122)
                                                                                                      	at com.android.okhttp.okio.GzipSource.<init>(GzipSource.java:64)
                                                                                                      	at com.android.okhttp.internal.http.HttpEngine.unzip(HttpEngine.java:484)
                                                                                                      	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:661)
                                                                                                      	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475)
                                                                                                      	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
                                                                                                      	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
                                                                                                      	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:106)
                                                                                                      	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:30)
                                                                                                      	at com.google.android.recaptcha.internal.zzbb.zzb(com.google.android.recaptcha:recaptcha@@18.3.0:16)
                                                                                                      	at com.google.android.recaptcha.internal.zzdk.invokeSuspend(com.google.android.recaptcha:recaptcha@@18.3.0:8)
                                                                                                      	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                      	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
                                                                                                      	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
                                                                                                      	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
                                                                                                      	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                                                                                                      	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
                                                                                                      	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
                                                                                                      	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
2023-10-03 12:42:53.976 29808-29823 System.err              app.debug                            W  StrictMode VmPolicy violation with POLICY_DEATH; shutting down.
2023-10-03 12:42:53.976 29808-29823 Process                 app.debug                            I  Sending signal. PID: 29808 SIG: 9
2023-10-03 12:42:54.053  1984-2477  InputDispatcher         system_server                        E  channel '58bdb81 app.debug/pe.io.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
---------------------------- PROCESS ENDED (29808) for package app.debug ----------------------------
```

### Library version

18.3.0

### Device

Motorola G8 Plus - Android 10

### Build.gradle
```
buildscript {
    ext {
        buildToolsVersion = "33.0.0"
        kotlinVersion = "1.9.0"
        minSdkVersion = 23
        compileSdkVersion = 33
        targetSdkVersion = 33
        ndkVersion = "23.1.7779620"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:7.3.1")
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath("com.google.gms:google-services:4.3.15")
        classpath("com.google.firebase:firebase-crashlytics-gradle:2.9.2")
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion")
    }
}
```

**Comment by mcorner** [comment]
Sorry for the delay.  We have pinpointed the source of this issue and it will be fixed int he next release.

You can exempt this strictmode violation for now:  StrictMode.setVmPolicy

**Comment by mcorner** [comment]
This issue was fixed a while ago. Thanks for the report.
